# Docker compose file for docker-coolq-alpine

version: '3'

services:
  coolq:
    build: .
    restart: always
    container_name: 'coolq'
    environment:
      DISPLAY_RESOLUTION: 960x544x24
      
    # expose vnc port to 2333
    ports:
      - '2333:5900'
