# This is a basic workflow to help you get started with Actions

name: Docker Compose

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compose-linux:
    runs-on: ubuntu-latest
    steps:

    # Checkout the repo
    - uses: actions/checkout@v2

    # Docker compose
    - name: Test Docker Compose
      run: docker-compose up --no-start
